[2025-02-02T14:40:33.408+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-02-02T14:40:33.428+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flights_pipeline.get_data_fly manual__2025-02-02T14:40:31.419071+00:00 [queued]>
[2025-02-02T14:40:33.434+0000] {taskinstance.py:2603} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flights_pipeline.get_data_fly manual__2025-02-02T14:40:31.419071+00:00 [queued]>
[2025-02-02T14:40:33.436+0000] {taskinstance.py:2856} INFO - Starting attempt 1 of 1
[2025-02-02T14:40:33.458+0000] {taskinstance.py:2879} INFO - Executing <Task(_PythonDecoratedOperator): get_data_fly> on 2025-02-02 14:40:31.419071+00:00
[2025-02-02T14:40:33.465+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=454) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-02T14:40:33.467+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'flights_pipeline', 'get_data_fly', 'manual__2025-02-02T14:40:31.419071+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/zdag.py', '--cfg-path', '/tmp/tmp5mz50b6r']
[2025-02-02T14:40:33.467+0000] {standard_task_runner.py:72} INFO - Started process 486 to run task
[2025-02-02T14:40:33.468+0000] {standard_task_runner.py:105} INFO - Job 5: Subtask get_data_fly
[2025-02-02T14:40:33.510+0000] {task_command.py:467} INFO - Running <TaskInstance: flights_pipeline.get_data_fly manual__2025-02-02T14:40:31.419071+00:00 [running]> on host 9c60fb534bff
[2025-02-02T14:40:33.576+0000] {taskinstance.py:3122} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flights_pipeline' AIRFLOW_CTX_TASK_ID='get_data_fly' AIRFLOW_CTX_EXECUTION_DATE='2025-02-02T14:40:31.419071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-02T14:40:31.419071+00:00'
[2025-02-02T14:40:33.577+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-02-02T14:40:35.276+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-02-02T14:40:35.283+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-02-02T14:40:35.288+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=flights_pipeline, task_id=get_data_fly, run_id=manual__2025-02-02T14:40:31.419071+00:00, execution_date=20250202T144031, start_date=20250202T144033, end_date=20250202T144035
[2025-02-02T14:40:35.331+0000] {local_task_job_runner.py:261} INFO - Task exited with return code 0
[2025-02-02T14:40:35.358+0000] {taskinstance.py:3891} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-02T14:40:35.369+0000] {local_task_job_runner.py:240} INFO - ::endgroup::
